CREATE TABLE notifications (
  id VARCHAR PRIMARY KEY NOT NULL,
  title VARCHAR NOT NULL,
  repo VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  unread BOOLEAN NOT NULL,
  done BOOLEAN NOT NULL
);
