CREATE TABLE prs (
  id INTEGER PRIMARY KEY NOT NULL,
  title VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  updated_at VARCHAR NOT NULL,
  unread BOOLEAN NOT NULL,
  repo_id INTEGER NOT NULL REFERENCES repos(id)
)
