ALTER TABLE notifications ADD COLUMN pr_state VARCHAR NOT NULL DEFAULT '';
ALTER TABLE notifications ADD COLUMN pr_number INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN pr_draft BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notifications ADD COLUMN pr_merged BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notifications ADD COLUMN pr_author VARCHAR NOT NULL DEFAULT '';
--    ;
